### ISSUE TITLE
Opdracht, presentatie & readme

### ISSUE THREAD

**Issue by KoopReynders** [mat1th/mat1th.github.io#15]
Wat ik mis in je Readme is een gestructureerde opbouw van je verhaal.
B.v. beginnen met wát de opdracht/demo is, welke hippe API je daarvoor gaat gebruiken/onderzoeken, en dan stap voor stap hoe je de PE hebt gedaan ...

Readme mist een duidelijk opbouw. Zie Moodle voor oplevercriteria.

**Comment by mat1th** [comment]
Ik heb de README.md verbeterd [#78757d1](https://github.com/mat1th/mat1th.github.io/commit/b0bdf8ff71133e67c55e1dbe78493283107992f8#diff-85785efd4285a9feca27f656df973793)
