### ISSUE TITLE
Link naar werkende demo ontbreekt

### ISSUE THREAD

**Issue by krijnhoetmer** [mat1th/mat1th.github.io#8]
Link gaat nu naar je homepage (waar ik ook een SSL error krijg trouwens).

**Comment by matth96** [comment]
Deze werkt nu wel. Mijn server heb ik van het weekend op nieuw moeten installeren. En deze was ik vergeten...

**Comment by krijnhoetmer** [comment]
Op https://beta.dolstra.me/search?search=test krijg ik nu alleen een Bad Gateway.

**Comment by matth96** [comment]
Dat heeft met mijn Ngnix instellingen te maken. Moet ik het fixen?

**Comment by krijnhoetmer** [comment]
Je live search doet het nu in ieder geval niet (omdat die dat via de server doet).

**Comment by mat1th** [comment]
Het is nu gefixt. De live search werkt nu zie: beta.dolstra.me
